language: cpp

matrix:
  include:
    # Test Docker based on Ubuntu 18.04 LTS + gcc
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh
    # Test OS X 10.12 + Xcode 9 + clang
    - os: osx
      osx_image: xcode9
      compiler: clang
      script:
        - sh Scripts/travis_build.sh

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == linux ]; then 
       sudo apt-get update -qq;
       sudo apt-get install -y --no-install-recommends libxrandr-dev libxi-dev libxxf86vm-dev libxinerama-dev libxcursor-dev libopenal-dev libvorbis-dev lcov;
       wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip;
       unzip glfw-3.2.1.zip && cd glfw-3.2.1; 
       cmake -DBUILD_SHARED_LIBS=true -DGLFW_BUILD_EXAMPLES=false -DGLFW_BUILD_TESTS=false -DGLFW_BUILD_DOCS=false .;
       sudo make -j $CPU_NUM install && cd ..;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
       brew update;
       brew install openal-soft;
       brew install glfw3;
       brew install lcov;
       wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz;
       tar xvf release-1.8.0.tar.gz;
       cd googletest-release-1.8.0;
       cmake .;
       sudo make -j $CPU_NUM install && cd ..;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
