language: cpp

matrix:
  include:
    - name: Test Docker based on Ubuntu 18.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh
    - name: Test Docker based on Ubuntu 18.10 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.cosmic cosmic
    - name: Test Docker based on Ubuntu 19.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.disco disco        
    - name: Test Docker based on Ubuntu 19.04 LTS + gcc-latest
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.disco.gcc-latest disco-gcc-latest
    - name: Test Docker based on Ubuntu 19.04 LTS + clang-latest
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.disco.clang-latest disco-clang-latest        
    - name: Test OS X 10.14 + Xcode 10.2 + clang
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - sh Scripts/travis_build.sh
    - name: Test OS X 10.14 + Xcode 10.2 + clang + codecov
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - BUILD_TYPE=Debug      
      script:
        - sh Scripts/travis_build_codecov.sh